apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-db-secret
  namespace: default
spec:
  # Sync mỗi 1 giờ
  refreshInterval: 1h
  secretStoreRef:
    name: fake-secret-store
    kind: SecretStore
  target:
    # Tên của K8s Secret sẽ được tạo
    name: external-pulled-secret
    creationPolicy: Owner
  data:
  - secretKey: db-username
    remoteRef:
      key: /myapp/database/username
  - secretKey: db-password
    remoteRef:
      key: /myapp/database/password
  - secretKey: api-key
    remoteRef:
      key: /myapp/api/key
