apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-webapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-webapp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http             # Named port from Deployment container
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "my-webapp.selectorLabels" . | nindent 4 }}
